---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: acr-secret
  namespace: capella
spec:
  encryptedData:
    .dockerconfigjson: AgBciylFfOinf3gZlgmdfhBjhwChPdJ640qT87P5QAH8M5QZ1TlzNgASffLBGKA9dhUq1CBAQ+dhFsBas0S7ALrGR9yje6KICrGHfY9X4FYpxjBiRLfB1A4vXmLdm84BFoyp4TrOjhopFTW3WhceeMUEyWUHneOncaKv9Vug4XP6nPF5jzgiBHuekz6M/PQzTLj78sEuowKdQDGPk4rdeuELd813j/w17ZYmD1ustGfqbTTaD4DI1XkMux2obpewLPCJ6J19KtuhrjCXE6l5vsk/9ZJHbHGVi1gPv539uTT13W5YCR1cYdPiOydu/v2TmwcOtBuQqTt8WhI1YwZpenj+1PyORJzvS83X+RpzgcCOa8XYC3u7NqzYeqH8Y+9TUfZQF5YizKgvqVRGj6dxk9eUQ5tAp5ys/Aucs29FdntYJy466Q/Qm/AnskwUaXNu141ydgKzcL4WAiBhpD1uEgv3zJLFSa8GMUp/3MgPREHv1N7iaQSGx5BWUY+z1PCG+q+3cFs9Kp/28F4wxr7VfM3RI4vOTTv48l6fkMKSCee25OwH/YqOwUJlt5urMBOaeRE1cX5J8/WZ/RHo7Bk0m5JpZVMdXI1XiZ8TLsIU/U+Ewpheeukd/sUWxkE4Wbzcix/WR5TOug+qTXmad/XcVVDule/dQWq6hEBufD1LtBqK/YRpczSJZ58qLM7yx58daTNcMechGb6XwwXz+mZttCUxD0bUjCFP4EgpadW6YNVVrhHODeXV/eIKCnL6QbSa+tmceyTmact6lzedt0nIt3qDs3Qb9ZVgGM6qTPNv3pMILVCKdVJ9anyLK11ogr+5XC3nWrDdaYK1IltdIDGgVtSL2rcPeEEvTi61ang=
  template:
    metadata:
      creationTimestamp: null
      name: acr-secret
      namespace: capella
    type: kubernetes.io/dockerconfigjson
