/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ChatHeader: typeof import('./src/components/chat/ChatHeader.vue')['default']
    ChatInputArea: typeof import('./src/components/chat/ChatInputArea.vue')['default']
    ChatMemberPanel: typeof import('./src/components/chat/ChatMemberPanel.vue')['default']
    ChatMessageBubble: typeof import('./src/components/chat/ChatMessageBubble.vue')['default']
    ChatMessageList: typeof import('./src/components/chat/ChatMessageList.vue')['default']
    ChatRoomList: typeof import('./src/components/chat/ChatRoomList.vue')['default']
    ChatWelcome: typeof import('./src/components/chat/ChatWelcome.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElResult: typeof import('element-plus/es')['ElResult']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSkeleton: typeof import('element-plus/es')['ElSkeleton']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    GlobalModal: typeof import('./src/components/common/GlobalModal.vue')['default']
    NavBar: typeof import('./src/components/nav/NavBar.vue')['default']
    NotificationPanel: typeof import('./src/components/quick/NotificationPanel.vue')['default']
    PersonalizationModal: typeof import('./src/components/quick/PersonalizationModal.vue')['default']
    QuickBar: typeof import('./src/components/quick/QuickBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}

// For TSX support
declare global {
  const ChatHeader: typeof import('./src/components/chat/ChatHeader.vue')['default']
  const ChatInputArea: typeof import('./src/components/chat/ChatInputArea.vue')['default']
  const ChatMemberPanel: typeof import('./src/components/chat/ChatMemberPanel.vue')['default']
  const ChatMessageBubble: typeof import('./src/components/chat/ChatMessageBubble.vue')['default']
  const ChatMessageList: typeof import('./src/components/chat/ChatMessageList.vue')['default']
  const ChatRoomList: typeof import('./src/components/chat/ChatRoomList.vue')['default']
  const ChatWelcome: typeof import('./src/components/chat/ChatWelcome.vue')['default']
  const ElButton: typeof import('element-plus/es')['ElButton']
  const ElCard: typeof import('element-plus/es')['ElCard']
  const ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
  const ElDivider: typeof import('element-plus/es')['ElDivider']
  const ElDropdown: typeof import('element-plus/es')['ElDropdown']
  const ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
  const ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
  const ElEmpty: typeof import('element-plus/es')['ElEmpty']
  const ElIcon: typeof import('element-plus/es')['ElIcon']
  const ElInput: typeof import('element-plus/es')['ElInput']
  const ElOption: typeof import('element-plus/es')['ElOption']
  const ElResult: typeof import('element-plus/es')['ElResult']
  const ElSelect: typeof import('element-plus/es')['ElSelect']
  const ElSkeleton: typeof import('element-plus/es')['ElSkeleton']
  const ElSwitch: typeof import('element-plus/es')['ElSwitch']
  const ElTabPane: typeof import('element-plus/es')['ElTabPane']
  const ElTabs: typeof import('element-plus/es')['ElTabs']
  const ElTag: typeof import('element-plus/es')['ElTag']
  const ElTooltip: typeof import('element-plus/es')['ElTooltip']
  const GlobalModal: typeof import('./src/components/common/GlobalModal.vue')['default']
  const NavBar: typeof import('./src/components/nav/NavBar.vue')['default']
  const NotificationPanel: typeof import('./src/components/quick/NotificationPanel.vue')['default']
  const PersonalizationModal: typeof import('./src/components/quick/PersonalizationModal.vue')['default']
  const QuickBar: typeof import('./src/components/quick/QuickBar.vue')['default']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
}