apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - postgres.yaml
  - redis.yaml
  - app.yaml
  - sealed/sealed-capella-env.yaml
  - sealed/sealed-acr-secret.yaml